FROM tenstartups/redis-commander
CMD redis-commander --redis-host $REDIS_PORT_6379_TCP_ADDR

# FROM node:0.10
# RUN npm install -g redis-commander
# CMD /redis-commander --redis-host ${REDIS_PORT_6379_TCP_ADDR}
